name: Build

on: [push, workflow_dispatch]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Typst
        uses: typst-community/setup-typst@v4
        
      - name: Build
        run: typst compile --font-path ${{ github.workspace }}/fonts main.typ main.pdf

      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: Rendered
          path: main.pdf

      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          name: "${{ github.ref_name }}"
          files: main.pdf
